### ISSUE TITLE
Failing test for flow.hello-world-optimization.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-examples#41]
The tests for `flow.hello-world-optimization` are failing. I believe this is due to some change in signac or signac-flow. This example needs to be fixed.

```
root:INFO:Testing 'flow.hello-world-optimization/'...
root:INFO:Executing code found in README.md file:
root:DEBUG:Copy project into temporary directory '/tmp/tmpvzepl7f_'.
root:DEBUG:Start test.
root:INFO: - python init.py
root:INFO: - python project.py run --num-passes=100
Using environment configuration: StandardEnvironment
ERROR: An exception was raised during operation spawn_new_simulations for job or aggregate with id db46ada2c91cf8fc760a92eba1a8f898.

Traceback (most recent call last):
  File "/opt/conda/envs/signac-examples/lib/python3.8/site-packages/flow/project.py", line 3117, in _execute_operation
    self._operations[operation.name](*operation._jobs)
  File "/opt/conda/envs/signac-examples/lib/python3.8/site-packages/flow/project.py", line 619, in __call__
    return self._op_func(*jobs)
  File "project.py", line 114, in spawn_new_simulations
    random.setstate(_convert_to_tuple(job.doc.rng))
  File "/opt/conda/envs/signac-examples/lib/python3.8/random.py", line 164, in setstate
    super().setstate(internalstate)
TypeError: state vector must be a tuple
Execute with '--show-traceback' or '--debug' to show the full traceback.
root:ERROR:Error at line: python project.py run --num-passes=100
Test failed.
```

**Comment by bdice** [comment]
Resolved by #42.
